[theme]
base = "light"
primaryColor = "#FF690F"
backgroundColor = "#FAFBFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#192024"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
runOnSave = false
maxUploadSize = 5

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
